pipeline {
    agent any
    stages{
        stage('terraform init'){
            steps {
                sh "terraform init"
            }
        }
    }
}

def getTerraformPath(){
    def tfHome= tool name: '', type: 'terraform'
    return tfHome
}